import { getDailyLaunches, getPairs, getStats } from '@/lib/data';
import { dailySeries, number } from '@/lib/format';
import { StatsRow } from '@/components/stats';
import { EmptyState } from '@/components/ui';
export const metadata = { title: 'Analytics' }; export const dynamic = 'force-dynamic';
export default async function Analytics() {
  const [stats, rows, pairs] = await Promise.all([getStats(), getDailyLaunches(), getPairs()]);
  const days = dailySeries(rows.data); const max = Math.max(1, ...days.map(d => d.count)); const top = pairs.data.slice(0, 10); const maxPair = Math.max(1, ...top.map(p => Number(p.launches)));
  return <section className="container page-section"><div className="page-heading"><span className="eyebrow">A WIDER VIEW</span><h1>The community,<br />by the numbers.</h1><p>Launches, pairings, and shared ETH. Activity you can follow.</p></div><StatsRow result={stats} /><div className="charts-grid"><section className="chart-panel"><div className="chart-heading"><div><span className="eyebrow">LAUNCH ACTIVITY</span><h2>A little more, each day.</h2></div><span className="chart-period">Last 30 days · UTC</span></div>{rows.state === 'ready' ? <><div className="bar-chart" role="img" aria-label={`${rows.data.length} launches in the past 30 days. Exact daily counts are in the table below.`}><div className="chart-y"><span>{max}</span><span>{Math.round(max / 2)}</span><span>0</span></div><div className="chart-bars">{days.map(day => <div className="chart-column" key={day.day}><div className="chart-bar" style={{ height: `${day.count / max * 100}%`, minHeight: day.count ? '3px' : '0' }} title={`${day.day}: ${day.count} launches`} /></div>)}</div></div><div className="chart-axis"><span>{days[0].day.slice(5)}</span><span>{days[14].day.slice(5)}</span><span>{days[29].day.slice(5)}</span></div>{!rows.data.length && <p className="data-caption">No launches recorded in this period.</p>}<details className="chart-table"><summary>View daily counts</summary><table><caption className="sr-only">Daily launches for the last 30 days</caption><thead><tr><th scope="col">Date (UTC)</th><th scope="col">Launches</th></tr></thead><tbody>{days.map(day => <tr key={day.day}><td>{day.day}</td><td>{day.count}</td></tr>)}</tbody></table></details></> : <EmptyState state={rows.state} />}</section><section className="chart-panel"><div className="chart-heading"><div><span className="eyebrow">STOCK PAIRINGS</span><h2>Where ideas gather.</h2></div><span className="chart-period">All time · top 10</span></div>{pairs.state === 'ready' && top.length ? <div className="horizontal-chart">{top.map(pair => <div className="horizontal-row" key={pair.symbol}><div><span>{pair.symbol}</span><strong>{number(Number(pair.launches))}</strong></div><div className="bar-track"><div style={{ width: `${Number(pair.launches) / maxPair * 100}%` }} /></div></div>)}</div> : <EmptyState state={pairs.state} noun="pairings" />}</section></div><p className="data-caption">Totals reflect the public database at page load. ETH paid includes completed payouts only; it does not represent an expected return.</p></section>;
}
